---
- name: Deploy .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ item.home }}/.gitconfig"
    owner: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
    mode: "0644"
    backup: true
  loop: "{{ target_users }}"
  loop_control:
    label: "{{ item.name }}"
